# Generated by Django 4.1.6 on 2023-02-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_otp_verify_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='qr_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.IntegerField()),
            ],
        ),
    ]
