# Generated by Django 4.1.6 on 2023-02-11 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_qr_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qr_code',
            old_name='qr_code',
            new_name='qr_code_value',
        ),
    ]
